Repository paketo-buildpacks/graalvm, pull requests merged in 2021-11, with the labels that each got.

#145 Fixes dependencies
  go.sum
Labels: type:task, semver:patch

#150 Fixed go.sum issue for Gomega 1.17 bump
  go.sum
Labels: type:dependency-upgrade, semver:patch

#157 Added buildpack.toml entries for CPEs & SBOM, bumped libpak, libcnb & libjvm
  buildpack.toml
  cmd/main/main.go
  go.mod
  go.sum
  graalvm/build_test.go
Labels: semver:minor, type:dependency-upgrade

#165 Added tests for API versions
  go.mod
  go.sum
  graalvm/build.go
  graalvm/build_test.go
  graalvm/jdk.go
Labels: type:bug, semver:patch
